AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Terrahaxs API Worker
Parameters:
  RollbarKey:
    Type: String
    Description: Secret Key
    Default: '{{resolve:secretsmanager:terrahaxs:SecretString:rollbar_key}}'
Resources:
  WorkerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      DockerContext: ./src
      DockerTag: latest
      Dockerfile: Dockerfile
    Properties:
      FunctionName: terrahaxs-api-worker
      FunctionUrlConfig:
        AuthType: NONE
      PackageType: Image
      Timeout: 900
      MemorySize: 2048
      EphemeralStorage:
        Size: 2048
      Tracing: Active
      Architectures:
        - arm64
      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        #Type: Linear10PercentEvery10Minutes
        Type: AllAtOnce
        #Alarms:
        #  - Ref: AliasErrorMetricGreaterThanZeroAlarm
        #  - Ref: LatestVersionErrorMetricGreaterThanZeroAlarm
      Environment:
        Variables:
          ROLLBAR_KEY: !Ref RollbarKey
          REGION: !Ref "AWS::Region"
          LOG_LEVEL: INFO
Outputs:
  WorkerFunctionEndpoint:
    Description: Worker API Endpoint
    Value: !GetAtt WorkerFunctionUrl.FunctionUrl